pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-backend1 && mvn install'
            }
        }
        stage('docker-build') {
            steps {
               sh 'cd coit-backend1 && docker build -t Aishathwaheeda/coit-backend1:v1 .'
               sh 'docker images' 
            }
        }
        stage('docker-push') {
            steps {
                sh 'echo "pushing docker image"'
                sh 'docker push aishathwaheeda/coit-backend1:v1'
            }
    }
}
}
